In [6]:
import pandas as pd
import plotly.express as px

In [3]:
df = pd.read_excel("C:\\Users\\acer\\Documents\\Data Analyst - Field Training Program\\Portfolio\\3. E-commerce\\outsourced_workforce_SLA_dap4\\01_data\\01_raw\\workforce_data.xlsx")

In [4]:
df.head()

,Employee_ID,Vendor,Role,Contract_Type,Saudization_Status,Performance_Score,SLA_Met,Attrition_Risk,Tenure_Months,Absenteeism_Days,Hourly_Rate_SAR
0,188332662,Riyadh Logistics Crew,Housekeeper,Project-Based,Expat,40,True,Medium,4,10,23
1,26677,Riyadh Logistics Crew,Security Guard,Part-Time,Saudi,84,True,Medium,8,9,35
2,7526626,Tabuk Facility Services,Warehouse Staff,Part-Time,Expat,71,True,Low,24,13,40
3,5406558,Saudi Hospitality Staffing,Construction Worker,Part-Time,Saudi,87,False,Medium,17,2,22
4,4095,Al-Rajhi Cleaning,Security Guard,Project-Based,Saudi,88,False,Medium,15,7,20

In [31]:
df['Employee_ID'].nunique()

1000

### 1. SLA Compliance by Vendor

In [7]:
sla_by_vendor = df.groupby("Vendor")['SLA_Met'].mean().reset_index()

In [9]:
fig1 = px.bar(sla_by_vendor, x='Vendor',y='SLA_Met',title="SLA Compliance by Vendor")
fig1.show()

### 2. Attrition Risk by Role

In [10]:
attrition_by_role = df.groupby(['Role','Attrition_Risk']).size().reset_index(name="Count")

In [12]:
df.groupby('Role')['Attrition_Risk'].size().reset_index()

                  Role  Attrition_Risk
0              Cleaner             168
1  Construction Worker             155
2               Driver             162
3          Housekeeper             154
4       Security Guard             175
5      Warehouse Staff             186

In [13]:
fig2 = px.bar(attrition_by_role, x='Role', y='Count', color='Attrition_Risk', barmode='stack', title="Attrition Risk by Role")
fig2.show()

### 3. Performance vs Saudization

In [14]:
performance_by_nationalization = df.groupby('Saudization_Status')['Performance_Score'].mean().reset_index()

In [16]:
fig3 = px.bar(performance_by_nationalization, x='Saudization_Status', y='Performance_Score', title='Performance Score by Saudization')
fig3.show()

### 4. Cost per Perfomance Point (Value for Money)

In [18]:
df['Cost_Performance_Ratio'] = df['Hourly_Rate_SAR'] / df['Performance_Score']

In [19]:
cost_efficiency_by_vendor = df.groupby("Vendor")['Cost_Performance_Ratio'].mean().reset_index()

In [20]:
fig4 = px.bar(cost_efficiency_by_vendor, x='Vendor', y='Cost_Performance_Ratio', title='Cost per Performance')
fig4.show()

### 5. Tenure vs Attrition Risk

In [21]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 12 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Employee_ID             1000 non-null   int64
 1   Vendor                  1000 non-null   object
 2   Role                    1000 non-null   object
 3   Contract_Type           1000 non-null   object
 4   Saudization_Status      1000 non-null   object
 5   Performance_Score       1000 non-null   int64
 6   SLA_Met                 1000 non-null   bool
 7   Attrition_Risk          1000 non-null   object
 8   Tenure_Months           1000 non-null   int64
 9   Absenteeism_Days        1000 non-null   int64
 10  Hourly_Rate_SAR         1000 non-null   int64
 11  Cost_Performance_Ratio  1000 non-null   float64
dtypes: bool(1), float64(1), int64(5), object(5)
memory usage: 87.0+ KB

In [ ]:
fig5 = px.scatter(df, x='Tenure_Months', y='Performance_Score', color="Attrition_Risk", title="Performance vs Tenure (Colored by Attrition Risk) ")
fig5.show()

In [28]:
df['SLA_Met'].mean()

np.float64(0.809)